---
- hosts: localhost
  become: true

  vars:
    system_packages:
      - git
      - make
      - build-essential
      - ssh
      - htop
      - net-tools
      - linux-tools-common
      - linux-tools-generic
      - glances
      - meld
      - parallel
      - nemo
      - tmux
      - fzf
      - jq


    snap_packages:
      - micro
      - fasd
      - gnome-calculator
      - pycharm-community
      - skype
      - slack
      - sublime-text
      - vlc
      - zotero-snap
      - spotify

    # snap packages requiring classic confinement
    snap_packages_classic:
      # code = visual studio code
      - code



  tasks:
    - name: "Install system dependencies"
      apt:
        pkg: "{{ system_packages }}"
        state: present
        update_cache: true

    - name: "Install snaps"
      snap:
        name: "{{ snap_packages }}"
        state: present

    - name: "Install snaps requiring classic confinement"
      snap:
        name: "{{ snap_packages_classic }}"
        state: present
        classic: true

    - name: "Install google chrome"
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
